Fixed conflicts with PHP 8.2, added type hinting for properties and…
wpovernight/wp-menu-cart pull request #53
Opened 2024-02-10 00:36 UTC by brualio

…refactoring.

Closes #52

2024-02-12 11:53 UTC, MohamadNateqi requested changes

2024-02-12 11:53 UTC, MohamadNateqi commented on includes/wpmenucart-edd.php
> +		}
This can be removed.

2024-02-12 11:53 UTC, MohamadNateqi commented on includes/wpmenucart-edd.php
>  			global $post;
This seems unused, and it would be good to remove it.

2024-02-12 11:53 UTC, MohamadNateqi commented on includes/wpmenucart-settings.php
> +			);
Why multiple lines?

2024-02-12 11:53 UTC, MohamadNateqi commented on includes/wpmenucart-settings.php
> +			'1' => isset( $wcmenucart_options['menu_name_1'] ) ? $wcmenucart_options['menu_name_1'] : '0'
WPCS - [For an array with elements in multiple lines, adding a comma at the end is recommended.](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#:~:text=Note%20the%20comma%20after%20the%20last%20array%20item%3A%20this%20is%20recommended%20because%20it%20makes%20it%20easier%20to%20change%20the%20order%20of%20the%20array%2C%20and%20makes%20for%20cleaner%20diffs%20when%20new%20items%20are%20added.)

2024-02-12 11:53 UTC, MohamadNateqi commented on wp-menu-cart.php
> +		$active_plugins        = $this->get_active_plugins();
This is an unused variable, and it would be good to remove it.

2024-02-13 11:35 UTC, BrunoPavlinic98 approved these changes
LGTM!

2024-02-14 08:33 UTC, merged